/**
 * Onboarding 配置 - 当 Supabase 不可用时作为 fallback
 */
export const MOCK_ONBOARDING_CONFIGS = [
  { step_order: 1, title: '怎么称呼你?', question_text: '怎么称呼你?', input_type: 'text', type: 'input', options: [] },
  {
    step_order: 2,
    title: '有什么日常问题会影响你?',
    subtitle: '(多选)',
    question_text: '有什么日常问题会影响你? (多选)',
    input_type: 'multi_select',
    type: 'multi-select',
    options: [
      { value: 'work_stress', label: '工作压力', emoji: '😩' },
      { value: 'financial', label: '经济压力', emoji: '💰' },
      { value: 'future', label: '未来规划', emoji: '📝' },
      { value: 'social', label: '社交关系', emoji: '👯' },
      { value: 'self_worth', label: '自我价值', emoji: '🤳' },
      { value: 'intimate', label: '亲密关系', emoji: '👩‍❤️‍👨' },
      { value: 'family', label: '家庭关系', emoji: '👨‍👩‍👧‍👦' },
      { value: 'health', label: '身体健康', emoji: '🏃' },
      { value: 'exam', label: '考学考公', emoji: '📚' },
      { value: 'sleep', label: '睡眠安歇', emoji: '🛌' },
    ],
  },
  {
    step_order: 3,
    title: '你的信仰历程处于哪个阶段?',
    question_text: '你的信仰历程处于哪个阶段?',
    input_type: 'single_select',
    type: 'single-select',
    options: [
      { value: 'new_believer', label: '初信萌芽' },
      { value: 'rooted', label: '生命扎根' },
      { value: 'growing', label: '持续成长' },
      { value: 'lifelong', label: '一生跟随' },
    ],
  },
  {
    step_order: 4,
    title: '你平时的灵修生活频率是?',
    question_text: '你平时的灵修生活频率是?',
    input_type: 'single_select',
    type: 'single-select',
    options: [
      { value: 'many_daily', label: '每日多次,恒切寻求' },
      { value: 'daily', label: '每日定时,静心灵修' },
      { value: 'weekly', label: '每周数次,稳定亲近' },
      { value: 'seeking', label: '正在寻求,渴望开始' },
    ],
  },
  {
    step_order: 5,
    title: '你的属灵生命中面临哪些挑战?',
    subtitle: '(多选)',
    question_text: '你的属灵生命中面临哪些挑战? (多选)',
    input_type: 'multi_select',
    type: 'multi-select',
    options: [
      { value: 'peace_calling', label: '寻求内心的平安与召命' },
      { value: 'god_will', label: '辨明上帝对我生活的旨意' },
      { value: 'faith', label: '渴望建立更坚固的信心' },
      { value: 'struggles', label: '诚实面对内心的挣扎与疑惑' },
      { value: 'prayer', label: '建立规律且持续的祷告习惯' },
    ],
  },
  {
    step_order: 6,
    title: '你对哪些章节主题更感兴趣?',
    subtitle: '(多选)',
    question_text: '你对哪些章节主题更感兴趣? (多选)',
    input_type: 'multi_select',
    type: 'multi-select',
    options: [
      { value: 'comfort', label: '安慰鼓励', emoji: '😊' },
      { value: 'wisdom', label: '智慧指引', emoji: '💡' },
      { value: 'pride', label: '戒骄戒躁', emoji: '🌈' },
      { value: 'workplace', label: '工作职场', emoji: '💼' },
      { value: 'relationships', label: '人际关系', emoji: '👥' },
      { value: 'resilience', label: '逆境坚韧', emoji: '⛰️' },
      { value: 'healing', label: '医治恢复', emoji: '➕' },
      { value: 'surrender', label: '安心交托', emoji: '🕊️' },
      { value: 'direction', label: '寻求方向', emoji: '🤔' },
      { value: 'deeper', label: '渴望更深', emoji: '🙏' },
      { value: 'freedom', label: '捆绑释放', emoji: '⛓️' },
      { value: 'passion', label: '重拾热情', emoji: '🔥' },
    ],
  },
  {
    step_order: 7,
    title: '光盐旅迹可以在哪些方面陪伴你成长?',
    subtitle: '(多选)',
    question_text: '光盐旅迹可以在哪些方面陪伴你成长? (多选)',
    input_type: 'multi_select',
    type: 'multi-select',
    options: [
      { value: 'prayer', label: '每日祷告引领' },
      { value: 'scripture', label: '深度经文启示' },
      { value: 'practical', label: '信仰视角的现实指引' },
      { value: 'companions', label: '属灵同伴的互助得力' },
      { value: 'watchfulness', label: '属灵生命督促与守望' },
    ],
  },
];
